[versions]
# plugins
agp = "8.4.0"
kotlin = "1.9.24"
gms = "4.4.1"
crashlytics = "2.9.9"
ksp = "1.9.24-1.0.20"
jetbrain-compose = "1.6.10"
dependencyguard = "0.5.0"

# libraries
jetpack-core-ktx = "1.13.1"
jetpack-activity-compose = "1.9.0"
jetpack-fragment = "1.7.0"
jetpack-lifecycle-runtime-ktx = "2.8.0"
jetpack-core-splashscreen = "1.0.1"
jetpack-navigation-compose = "2.8.0-beta01"
jetpack-junit = "1.1.5"
jetpack-espresso-core = "3.5.1"
jetpack-compose-bom = "2024.05.00"
jetpack-compose = "1.6.7"
jetpack-compose-compiler = "1.5.14"
jetpack-compose-material3 = "1.2.1"
jetpack-datastore-preferences = "1.1.1"
junit = "5.10.2"
kotlinx-coroutines-core = "1.8.1"
kotlinx-datetime = "0.5.0"
kotlinx-collections-immutable = "0.3.7"
firebase-bom = "33.0.0"
koin = "3.5.6"
annotation = "1.8.0"
appcompat = "1.6.1"
material = "1.12.0"
javapoet = "1.13.0"
timber = "5.0.1"
detekt = "1.23.6"
twitter-compose-rules = "0.0.26"
supabase = "2.3.1"
ktor = "2.3.11"
serialization = "1.6.3"
mockk = "1.13.11"
coil = "2.6.0"
turbine = "1.1.0"
roborazzi = "1.16.0"
robolectric = "4.12.1"
accompanist = "0.34.0"

[libraries]
androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlinPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrainCompoesPlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "jetbrain-compose" }
kspPlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gmsPlugin = { group = "com.google.gms", name = "google-services", version.ref = "gms" }
crashlyticsPlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "crashlytics" }
detektPlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
kotlinSerializationPlugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
roborazziGradlePlugin = { group = "io.github.takahirom.roborazzi", name = "roborazzi-gradle-plugin", version.ref = "roborazzi" }

# jetpack
jetpack-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "jetpack-core-ktx" }
jetpack-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "jetpack-activity-compose" }
jetpack-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "jetpack-fragment" }
jetpack-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "jetpack-navigation-compose" }
jetpack-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "jetpack-lifecycle-runtime-ktx" }
jetpack-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "jetpack-core-splashscreen" }
jetpack-junit = { group = "androidx.test.ext", name = "junit", version.ref = "jetpack-junit" }
jetpack-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "jetpack-espresso-core" }
jetpack-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "jetpack-compose-bom" }
jetpack-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "jetpack-compose" }
jetpack-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "jetpack-compose" }
jetpack-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "jetpack-compose" }
jetpack-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "jetpack-compose" }
jetpack-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "jetpack-compose" }
jetpack-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "jetpack-compose" }
jetpack-compose-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "jetpack-compose" }
jetpack-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "jetpack-compose-material3" }
jetpack-compose-material3-windowsizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "jetpack-compose-material3" }
jetpack-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "jetpack-datastore-preferences" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# junit
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }

# kotlin
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

# firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-common = { module = "com.google.firebase:firebase-common" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }

# supabase
supabase-db = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt", version.ref = "supabase" }
supabase-auth = { group = "io.github.jan-tennert.supabase", name = "compose-auth", version.ref = "supabase" }
supabase-auth-ui = { group = "io.github.jan-tennert.supabase", name = "compose-auth-ui", version.ref = "supabase" }

# ktor
ktor = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }

# koin
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }

# material
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# detekt
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
twitter-compose-rules = { group = "com.twitter.compose.rules", name = "detekt", version.ref = "twitter-compose-rules" }

# mockk
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }

# coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# turbine
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# roborazzi
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-junit-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }

# robolectric
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# accompanist
accompanist-testharness = { group = "com.google.accompanist", name = "accompanist-testharness", version.ref = "accompanist" }

javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[plugins]
androidGradlePlugin = { id = "com.android.application", version.ref = "agp" }
androidGradleLibraryPlugin = { id = "com.android.library", version.ref = "agp" }
kotlinPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gmsPlugin = { id = "com.google.gms.google-services", version.ref = "gms" }
crashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detektPlugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinSerializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinParcelizePlugin = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
dependencyGuardPlugin = { id = "com.dropbox.dependency-guard", version.ref = "dependencyguard" }
roborazziPlugin = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

wihd-kotlin = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.kotlin", version = "unspecified" }
wihd-android = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.android", version = "unspecified" }
wihd-library = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.library", version = "unspecified" }
wihd-test = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.test", version = "unspecified" }
wihd-compose = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.compose", version = "unspecified" }
wihd-firebase = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.firebase", version = "unspecified" }
wihd-detekt = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.detekt", version = "unspecified" }
wihd-serialization = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.serialization", version = "unspecified" }
wihd-parcelize = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.parcelize", version = "unspecified" }

wihd-bundle-feature = { id = "parkjonghun.whatishedoingwithandroid.mobile.convention.feature", version = "unspecified" }

[bundles]
plugins = [
    "androidGradlePlugin",
    "kotlinPlugin",
    "jetbrainCompoesPlugin",
    "kspPlugin",
    "gmsPlugin",
    'detektPlugin',
    "kotlinSerializationPlugin",
    "crashlyticsPlugin",
]
